name: Build unsigned ipa

on:
  workflow_dispatch:   # 手动触发
  push:
    tags:              # 打 tag 时自动触发
      - '*'

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.2"

jobs:
  build-rustdesk-ios:
    name: build rustdesk unsigned ipa
    runs-on: macos-13
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install nasm yasm

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: aarch64-apple-ios
          components: "rustfmt"

      - name: Build rustdesk lib
        run: |
          rustup target add aarch64-apple-ios
          cargo build --features flutter,hwcodec --release --target aarch64-apple-ios --lib

      - name: Build unsigned ipa
        run: |
          cd flutter
          flutter build ipa --release --no-codesign

      - name: Upload ipa to Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: ${{ github.ref_name }}
          files: |
            flutter/build/ios/ipa/*.ipa
