name: Build iOS IPA for RustDesk

on:
  workflow_dispatch:  # 允许手动触发
  push:
    tags:
      - 'v*'  # 当推送以v开头的tag时自动触发

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.24.5"
  TAG_NAME: "${{ github.ref_name }}"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-rustdesk-ios:
    name: Build iOS IPA
    runs-on: macos-13
    needs: [generate-bridge]
    
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install nasm yasm

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Patch flutter
        run: |
          cd $(dirname $(dirname $(which flutter)))
          [[ "3.24.5" == ${{env.FLUTTER_VERSION}} ]] && git apply ${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --triplet arm64-ios \
            --x-install-root="$VCPKG_ROOT/installed"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              echo "======"
              cat "$_1"
              echo "======"
              echo ""
            done
            exit 1
          fi
          head -n 100 "${VCPKG_ROOT}/buildtrees/ffmpeg/build-arm64-ios-rel-out.log" || true
        shell: bash

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: aarch64-apple-ios
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rustdesk-lib-cache-ios
          key: aarch64-apple-ios

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Build rustdesk lib
        run: |
          rustup target add aarch64-apple-ios
          cargo build --features flutter,hwcodec --release --target aarch64-apple-ios --lib

      - name: Build iOS app archive
        shell: bash
        run: |
          cd flutter
          # 构建 iOS archive (不会生成 IPA，因为没有签名)
          flutter build ipa --release --no-codesign
          
          # 手动创建 IPA 文件
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r RustDesk-unsigned.ipa Payload
          cd ../../..
          echo "IPA_PATH=flutter/build/ios/ipa/RustDesk-unsigned.ipa" >> $GITHUB_ENV

      - name: Check IPA file
        run: |
          if [ -f "${{ env.IPA_PATH }}" ]; then
            echo "IPA file created successfully"
            ls -la ${{ env.IPA_PATH }}
          else
            echo "Failed to create IPA file"
            # 列出构建目录内容以便调试
            find flutter/build/ios -type f -name "*.app" -o -name "*.xcarchive" | head -10
            exit 1
          fi

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-ios-unsigned-${{ env.TAG_NAME }}
          path: ${{ env.IPA_PATH }}
          retention-days: 30

      - name: Create Release and Upload IPA
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.IPA_PATH }}
          draft: false
          prerelease: false
          body: |
            Unsigned iOS IPA for RustDesk
            - Build Date: ${{ github.event.head_commit.timestamp || github.run_started_at }}
            - Commit: ${{ github.sha }}
            - Flutter Version: ${{ env.FLUTTER_VERSION }}
            - Rust Version: ${{ env.RUST_VERSION }}
            - Tag: ${{ env.TAG_NAME }}
            
            **Note:** This is an unsigned IPA file. You'll need to:
            1. Resign it with your own Apple Developer account
            2. Use tools like Cydia Impactor or AltStore to install on jailbroken devices
            3. For development purposes, you can use Xcode to install on your own devices

      - name: Output Build Info
        run: |
          echo "=== Build Information ==="
          echo "Tag: ${{ env.TAG_NAME }}"
          echo "IPA Path: ${{ env.IPA_PATH }}"
          if [ -f "${{ env.IPA_PATH }}" ]; then
            echo "IPA Size: $(du -h ${{ env.IPA_PATH }} | cut -f1)"
          fi
          if startsWith(github.ref, 'refs/tags/'); then
            echo "Release created with IPA file"
          else
            echo "Manual build - IPA available as artifact"
          fi
          echo "Artifact name: rustdesk-ios-unsigned-${{ env.TAG_NAME }}"
